AY2223S2-CS2103T-T11-4/tp

- docs/UserGuide.md
> Added User guide

- docs/_config.yml
- docs/_sass/minima/_base.scss
Edits _config.yml file and _base.scss to reflect our project name and repository
> Updates project configuration

- docs/DeveloperGuide.md
- docs/UserGuide.md
Edit the UserGuide to remove instances of "AB search". Edit the Developer guide to include our own functionalities.
> Edited the UserGuide and Developer guide

- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/commands/RemarkCommand.java
- src/main/java/seedu/address/logic/parser/AddCommandParser.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/model/person/Remark.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/main/java/seedu/address/storage/JsonAdaptedPerson.java
- src/main/java/seedu/address/ui/PersonCard.java
- src/main/resources/view/PersonListCard.fxml
- src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
- src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
- src/test/java/seedu/address/testutil/PersonBuilder.java
- src/test/java/seedu/address/testutil/TypicalPersons.java
Adds remark function to the app
> Remark functionality

- src/main/java/seedu/address/logic/commands/AddCommand.java
- src/main/resources/view/PersonListCard.fxml
1. Made the address fully visible.
2. Change the display order of a person's information.
3. Adjust the hint message of add command.
> Simple UI Adjustment

- src/main/java/seedu/address/commons/core/Messages.java
- src/main/java/seedu/address/logic/commands/DeleteCommand.java
- src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
- src/main/java/seedu/address/model/person/Nric.java
- src/main/java/seedu/address/model/person/Person.java
- src/test/java/seedu/address/logic/LogicManagerTest.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Changed delete command to delete by patient's NRIC (eg delete i/NRIC)
Updated test cases accordingly.
> Resolves #32

- src/main/java/seedu/address/logic/commands/AddCommand.java
- src/main/java/seedu/address/ui/MainWindow.java
- src/main/resources/view/CommandBox.fxml
- src/main/resources/view/MainWindow.fxml
- src/main/resources/view/PersonListCard.fxml
- src/main/resources/view/PersonListPanel.fxml
- src/main/resources/view/ResultDisplay.fxml
**1. Invert the command_box and result_play zones.
2. Display the above 2 zones horizontally.
3. Delete the status_bar (file path) part.**
Whether to adopt this version should be discussed.
But the layout is basically like below:
> New Version UI

- docs/DeveloperGuide.md
- docs/UserGuide.md
Changed some minor mistakes and formats to keep consistency throughout the UG.
> UG amendment and DG update

- src/main/java/seedu/address/commons/core/Messages.java
- src/main/java/seedu/address/logic/commands/DeleteCommand.java
- src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/person/Nric.java
- src/main/java/seedu/address/model/person/UniquePersonList.java
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
- src/test/java/seedu/address/logic/commands/BackupCommandTest.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
- src/test/java/seedu/address/model/person/UniquePersonListTest.java
1)  Add ability to delete multiple patient records at once
2)  Add findPersonByNric function to facilitate deleting of patient records
3) Updated tests for delete command
4) Added tests for findPersonByNric
> Delete Command Functionality

- docs/DeveloperGuide.md
- docs/UserGuide.md
- src/main/java/seedu/address/logic/commands/FindCommand.java
- src/main/java/seedu/address/logic/parser/FindCommandParser.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Edit syntax of Find Command notation to match Add Command
> Find command notation

- src/test/java/seedu/address/model/person/NricTest.java
Closes #66 
Added tests for the Nric class to check for validity of constructor, similar to other tests for Name, Address, Email etc. objects.
> Add tests for valid/invalid Nric formats from input

- src/main/java/seedu/address/logic/commands/AddCommand.java
Simple fix on the hint message.
> Fix the add hint message error.

- src/main/java/seedu/address/commons/core/Messages.java
- src/main/java/seedu/address/logic/commands/ViewCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/ViewCommandParser.java
- src/test/java/seedu/address/logic/commands/ViewCommandTest.java
- src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
- Added logic for view command 
- Updated test cases accordingly
> Added logic for view command

- src/main/java/seedu/address/logic/parser/FindCommandParser.java
- src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/commands/FindCommandTest.java
- src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
- src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
- src/test/java/seedu/address/testutil/TypicalPersons.java
> Add Test cases

- src/main/java/seedu/address/commons/core/Messages.java
- src/main/java/seedu/address/logic/commands/DeleteCommand.java
- src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/test/java/seedu/address/logic/LogicManagerTest.java
- src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
- src/test/java/seedu/address/logic/parser/ParserUtilTest.java
- Changed from a single prefix with space in between NRIC to multiple NRIC prefixes
- Updated test cases accordingly
> Refactored delete command to allow multiple NRIC prefix

- docs/team/creationsv2.md
Updated PPP for draft release.
> Update PPP for Creationsv2

- src/main/java/seedu/address/commons/core/Messages.java
> Fix error message for view command.

- src/main/java/seedu/address/logic/commands/AddCommand.java
> Fix duplicate person message being "Address Book".

- src/main/java/seedu/address/commons/core/Messages.java
> Fix grammar for Messages.java

- docs/UserGuide.md
Fixes #161
Fixes #189 
Fixes #200
> Update UG to fix documentation bugs.

- src/main/java/seedu/address/logic/commands/FindCommand.java
- src/main/java/seedu/address/logic/parser/FindCommandParser.java
- src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Fixes #176 
Also updated test cases accordingly.
> Fix find command error message for multiple attributes

- src/main/java/seedu/address/model/person/DateOfBirth.java
- src/test/java/seedu/address/model/person/DateOfBirthTest.java
Checks for 29 feb in leap years, inputting invalid days for the wrong months will now generate a warning.
> Fix date of birth to check for invalid outputs.

- docs/UserGuide.md
- Consistent spacing for notes section and added spacing for setup
- Updated command summary for edit and add command
- Added instructions on how to use drug allergy field if patient does not have any drug allergies
Resolve #166, resolve #170, resolve #198
> Update UG to fix documentation flaws

- src/main/java/seedu/address/logic/Logic.java
- src/main/java/seedu/address/logic/LogicManager.java
- src/main/java/seedu/address/ui/MainWindow.java
- Now view command updates filtered person predicate to list everyone.
> Fixes the view command -> edit error bug

- docs/DeveloperGuide.md
- docs/team/dawg420.md
> PPP updates
